{% set name = "IRMA" %}
{% set version = "1.0.3-rsv" %}
{% set hash_type = "sha256" %}
{% set hash_value = "6F6DA4F9FAFDF3FC6A6CA5C8506DE0790C6BF0B4BC26E86504285FD1EF18842D" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ammaraziz/conda_irma_recipe/raw/main/flu-amd-rsv.7z
  {{ hash_type }}: {{ hash_value }}
  patches:
    - irma-fix-bin-cmds.patch
    - label-fix-bin-cmds.patch
    - irma-check-dir-writable.patch

build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
  run:
    - perl
    - r-base >=3.5.1
    - parallel >=20181022
    - pigz >=2.3.4
    - blat >=35
    - samtools >=1.2
    - fasttree >=2.1.3
    - muscle >=3.8.1551
    - minimap2 >=2.17
    - zip >=3.0

test:
  files:
    - test1.fa
    - test2.fastq

about:
  home: https://wonder.cdc.gov/amd/flu/irma/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: "IRMA: Iterative Refinement Meta-Assembler for the robust assembly, variant calling, and phasing of highly variable RNA viruses."
license_family: GPL3
