{% set name = "IRMA" %}
{% set version = "1.0.3.rsv" %}
{% set hash_type = "sha256" %}
{% set hash_value = "6e912d6e469a51c154dc1c1521e79a7b2f7950292ba1f000916102a30b66c1c0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ammaraziz/conda_irma_recipe/raw/main/flu-amd-rsv.zip
  {{ hash_type }}: {{ hash_value }}
  patches:
    - irma-fix-bin-cmds.patch
    - label-fix-bin-cmds.patch
    - irma-check-dir-writable.patch

build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
  run:
    - perl
    - r-base >=3.5.1
    - parallel >=20181022
    - pigz >=2.3.4
    - blat >=35
    - samtools >=1.2
    - fasttree >=2.1.3
    - muscle >=3.8.1551
    - minimap2 >=2.17
    - zip >=3.0

about:
  home: https://github.com/ammaraziz/wfi
  license: GNU General Public License v3 or later (GPLv3+)
  summary: "IRMA v1.0.3 - modified to include RSV"
license_family: GPL3
